version: '2'
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: false
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 45
  identical-code:
    enabled: true
    config:
      threshold: 45
plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 2
  rubocop:
    enabled: false
  eslint:
    enabled: false
exclude_patterns:
  - 'android/'
  - 'ios/'
  - 'coverage/'
  - '**/*.test.*'
